<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Re: mod_python 3.3.1 bug report
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Re%3A%20mod_python%203.3.1%20bug%20report&In-Reply-To=485b27c5.3c432c0a.10e7.7420SMTPIN_ADDED%40mx.google.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025371.html">
   <LINK REL="Next"  HREF="025373.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Re: mod_python 3.3.1 bug report</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Re%3A%20mod_python%203.3.1%20bug%20report&In-Reply-To=485b27c5.3c432c0a.10e7.7420SMTPIN_ADDED%40mx.google.com"
       TITLE="[mod_python] Re: mod_python 3.3.1 bug report">graham.dumpleton at gmail.com
       </A><BR>
    <I>Thu Jun 19 23:49:58 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="025371.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
        <LI>Next message: <A HREF="025373.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25372">[ date ]</a>
              <a href="thread.html#25372">[ thread ]</a>
              <a href="subject.html#25372">[ subject ]</a>
              <a href="author.html#25372">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Instead of repr(), try str() then. Also try:

  line[:-1].encode('UTF-8')

I think.

You might add at same level of indent in that loop:

  import sys
  print &gt;&gt; sys.stderr, repr(line[:-1])
  sys.stderr.flush()

This should hopefully flush out to Apache logs and by pass the
mod_python error log function.

If still no luck, there may be some issue with Python installation, not sure.

Graham

2008/6/20 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
&gt;<i> Graham,
</I>&gt;<i>
</I>&gt;<i> This result looks similar (if not identical).
</I>&gt;<i>
</I>&gt;<i> -Mike
</I>&gt;<i>
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [notice] mod_python (pid=3332,
</I>&gt;<i> interpreter='localhost'): Importing module 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] mod_python (pid=3332,
</I>&gt;<i> interpreter='localhost', phase='PythonHandler', handler='mptest'):
</I>&gt;<i> Application error
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;<i> 'localhost'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;<i> 'D:/htdocs'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] URI:
</I>&gt;<i> '/Python/mptest.py'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;<i> 'D:/htdocs/Python/'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;<i> 'D:/htdocs/Python/mptest.py'
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Traceback (most recent
</I>&gt;<i> call last):
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;<i> silent=hlist.silent)
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 1202, in _process_target\n    module = import_module(module_name, path=path)
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 296, in import_module\n    log, import_path)
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 680, in import_module\n    execfile(file, module.__dict__)
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>  File &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;, line
</I>&gt;<i> 1784, in ReportError
</I>&gt;<i>    log_error(repr(line[:-1]), flags)                           # was:
</I>&gt;<i>  log_error(line[:-1], flags)
</I>&gt;<i> TypeError: argument 1 must be string without null bytes or None, not str
</I>&gt;<i> [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;<i> Dispatch() returned non-integer.
</I>&gt;<i>
</I>&gt;<i> At 11:19 PM 6/19/2008, Graham Dumpleton wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Please use reply-all and keep followups on mailing list.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Anyway, read message wrong first time. It isn't log_error() in your
</I>&gt;&gt;<i> code which is problem, but code in mod_python used to display error
</I>&gt;&gt;<i> tracebacks. In particular:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>            tb = traceback.format_exception(etype, evalue, etb)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>            for line in tb:
</I>&gt;&gt;<i>                log_error(line[:-1], flags)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I can only image that somehow a Unicode character string has gotten
</I>&gt;&gt;<i> into traceback message from Python.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> What I suggest you do is modify the importer.py in mod_python
</I>&gt;&gt;<i> installed source so that that log_error() call reads:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>                log_error(repr(line[:-1]), flags)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> That should show you true error which is first occurring. Unicode
</I>&gt;&gt;<i> strings shouldn't be an issue then as are converting it all to
</I>&gt;&gt;<i> displayable latin.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Please don't though just fix the error if in your code if obvious,
</I>&gt;&gt;<i> instead post the resultant error traceback to list so can see how
</I>&gt;&gt;<i> unicode string is getting into traceback.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Graham
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2008/6/20 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
</I>&gt;&gt;<i> &gt; Graham,
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; The results look identical to me... (see immediately below)
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; -Mike
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [notice] mod_python (pid=3332,
</I>&gt;&gt;<i> &gt; interpreter='localhost'): Importing module
</I>&gt;&gt;<i> &gt; 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] mod_python
</I>&gt;&gt;<i> &gt; (pid=3332,
</I>&gt;&gt;<i> &gt; interpreter='localhost', phase='PythonHandler', handler='mptest'):
</I>&gt;&gt;<i> &gt; Application error
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;&gt;<i> &gt; 'localhost'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;&gt;<i> &gt; 'D:/htdocs'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] URI:
</I>&gt;&gt;<i> &gt; '/Python/mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;&gt;<i> &gt; 'D:/htdocs/Python/'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;&gt;<i> &gt; 'D:/htdocs/Python/mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Traceback (most
</I>&gt;&gt;<i> &gt; recent
</I>&gt;&gt;<i> &gt; call last):
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;&gt;<i> &gt; silent=hlist.silent)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1202, in _process_target\n    module = import_module(module_name,
</I>&gt;&gt;<i> &gt; path=path)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 296, in import_module\n    log, import_path)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 680, in import_module\n    execfile(file, module.__dict__)
</I>&gt;&gt;<i> &gt; Traceback (most recent call last):
</I>&gt;&gt;<i> &gt;  File &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1784, in ReportError
</I>&gt;&gt;<i> &gt;    log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt; TypeError: argument 1 must be string without null bytes or None, not str
</I>&gt;&gt;<i> &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;&gt;<i> &gt; Dispatch() returned non-integer.
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; ==========================================================================
</I>&gt;&gt;<i> &gt; At 09:33 PM 6/19/2008, you wrote:
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; What happens when you use:
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt;  from mod_python import apache
</I>&gt;&gt;<i> &gt;&gt;  apache.log_error('handler')
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; instead?
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; Graham
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; 2008/6/16 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; 32 bit Windows Vista, Apache 2.2.8, mod_python 3.3.1, python 2.5.2.2
</I>&gt;&gt;<i> &gt;&gt; &gt; (r252:60911)
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; I received a 500 error from Apache httpd while attempting to get
</I>&gt;&gt;<i> &gt;&gt; &gt; mod_python working on Windows Vista.  Following are entries from
</I>&gt;&gt;<i> &gt;&gt; &gt; error.log, httpd.conf, and the Python source (mptest.py) used as a
</I>&gt;&gt;<i> &gt;&gt; &gt; test
</I>&gt;&gt;<i> &gt;&gt; &gt; case.  The error
</I>&gt;&gt;<i> &gt;&gt; &gt; occurs within importer.py (part of the mod_pyton site-package).
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; Apache httpd error log:
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [notice] mod_python (pid=3708,
</I>&gt;&gt;<i> &gt;&gt; &gt; interpreter='localhost'): Importing module
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] mod_python
</I>&gt;&gt;<i> &gt;&gt; &gt; (pid=3708, interpreter='localhost', phase='PythonHandler',
</I>&gt;&gt;<i> &gt;&gt; &gt; handler='mptest'): Application error
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'localhost'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] URI:
</I>&gt;&gt;<i> &gt;&gt; &gt; '/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs/Python/'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Traceback (most
</I>&gt;&gt;<i> &gt;&gt; &gt; recent call last):
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line 1537, in HandlerDispatch\n default=default_handler, arg=req,
</I>&gt;&gt;<i> &gt;&gt; &gt; silent=hlist.silent)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line 1202, in _process_target\n module = import_module(module_name,
</I>&gt;&gt;<i> &gt;&gt; &gt; path=path)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line 296, in import_module\n log, import_path)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line 680, in import_module\n execfile(file, module.__dict__)
</I>&gt;&gt;<i> &gt;&gt; &gt; Traceback (most recent call last): File
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line 1784, in ReportError log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt;&gt; &gt; TypeError: argument 1 must be string without null bytes or None, not
</I>&gt;&gt;<i> &gt;&gt; &gt; str
</I>&gt;&gt;<i> &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;&gt;<i> &gt;&gt; &gt; Dispatch() returned non-integer.
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; --------------------------------------------------------------------------------
</I>&gt;&gt;<i> &gt;&gt; &gt; httpd.conf entries:
</I>&gt;&gt;<i> &gt;&gt; &gt; LoadModule python_module modules/mod_python.so
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &lt;Directory D:\htdocs\Python&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; AddHandler      mod_python .py
</I>&gt;&gt;<i> &gt;&gt; &gt;        PythonHandler   mptest
</I>&gt;&gt;<i> &gt;&gt; &gt;        PythonDebug
</I>&gt;&gt;<i> &gt;&gt; &gt; On
</I>&gt;&gt;<i> &gt;&gt; &gt; &lt;/Directory&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; --------------------------------------------------------------------------------
</I>&gt;&gt;<i> &gt;&gt; &gt; Python source (in mptest.py):
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; from mod_python import apache
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; def handler(req):
</I>&gt;&gt;<i> &gt;&gt; &gt;         req.log_error('handler')
</I>&gt;&gt;<i> &gt;&gt; &gt;         req.content_type =
</I>&gt;&gt;<i> &gt;&gt; &gt; 'text/plain'
</I>&gt;&gt;<i> &gt;&gt; &gt;         req.write('HelloWorld\n')
</I>&gt;&gt;<i> &gt;&gt; &gt;         return apache.OK
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; No virus found in this incoming message.
</I>&gt;&gt;<i> &gt;&gt; Checked by AVG.
</I>&gt;&gt;<i> &gt;&gt; Version: 8.0.100 / Virus Database: 270.4.0/1509 - Release Date:
</I>&gt;&gt;<i> &gt;&gt; 6/19/2008
</I>&gt;&gt;<i> &gt;&gt; 8:00 AM
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> No virus found in this incoming message.
</I>&gt;&gt;<i> Checked by AVG.
</I>&gt;&gt;<i> Version: 8.0.100 / Virus Database: 270.4.0/1509 - Release Date: 6/19/2008
</I>&gt;&gt;<i> 8:00 AM
</I>&gt;<i>
</I>&gt;<i>
</I></PRE>




<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025371.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
	<LI>Next message: <A HREF="025373.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25372">[ date ]</a>
              <a href="thread.html#25372">[ thread ]</a>
              <a href="subject.html#25372">[ subject ]</a>
              <a href="author.html#25372">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
