<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] &quot;Cannot re-init internal module exceptions&quot;
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To=3B3211AE.D34A61DC%40livinglogic.de">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000873.html">
   <LINK REL="Next"  HREF="000871.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] &quot;Cannot re-init internal module exceptions&quot;</H1>
    <B>Tom Emerson</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To=3B3211AE.D34A61DC%40livinglogic.de"
       TITLE="[mod_python] &quot;Cannot re-init internal module exceptions&quot;">tree at basistech.com
       </A><BR>
    <I>Thu Jun 21 12:23:13 EST 2001</I>
    <P><UL>
        <LI>Previous message: <A HREF="000873.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
        <LI>Next message: <A HREF="000871.html">[mod_python] import module via publisher
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#874">[ date ]</a>
              <a href="thread.html#874">[ thread ]</a>
              <a href="subject.html#874">[ subject ]</a>
              <a href="author.html#874">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>=?iso-8859-1?Q?Walter_D=F6rwald?= writes:
&gt;<i> &gt;     import exceptions
</I>&gt;<i> &gt; [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: ImportError: Cannot re-init internal module exceptions
</I>&gt;<i> 
</I>&gt;<i> Could this be related to Python bug #422004?
</I>&gt;<i> 
</I>&gt;<i> <A HREF="http://sourceforge.net/tracker/?group_id=5470&amp;atid=105470&amp;func=detail&amp;aid=422004">http://sourceforge.net/tracker/?group_id=5470&amp;atid=105470&amp;func=detail&amp;aid=422004</A>
</I>
Yes, it appears to be exactly that problem. After rebuilding Python
with the patch given in the bug report I'm able to use AHTS from
within mod_python. Sweet.

Thanks!

    -tree

-- 
Tom Emerson                                          Basis Technology Corp.
Sr. Sinostringologist                              <A HREF="http://www.basistech.com">http://www.basistech.com</A>
  &quot;Beware the lollipop of mediocrity: lick it once and you suck forever&quot;

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000873.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
	<LI>Next message: <A HREF="000871.html">[mod_python] import module via publisher
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#874">[ date ]</a>
              <a href="thread.html#874">[ thread ]</a>
              <a href="subject.html#874">[ subject ]</a>
              <a href="author.html#874">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
