<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] &quot;Cannot re-init internal module exceptions&quot;
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="008264.html">
   <LINK REL="Next"  HREF="008269.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
<table border=0 width="100%"><tr><td valign="top">
   <H1>[mod_python] &quot;Cannot re-init internal module exceptions&quot;</H1>
    <B>Tom Emerson</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To="
       TITLE="[mod_python] &quot;Cannot re-init internal module exceptions&quot;">tree at basistech.com
       </A><BR>
    <I>Thu Jun 21 09:29:16 EST 2001</I>
    <P><UL>
        <LI>Previous message: <A HREF="008264.html">[mod_python] Any open-source applications?
</A></li>
        <LI>Next message: <A HREF="008269.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8266">[ date ]</a>
              <a href="thread.html#8266">[ thread ]</a>
              <a href="subject.html#8266">[ subject ]</a>
              <a href="author.html#8266">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Greetings.

I'm attempting to get mod_python working with the AHTS template engine
(<A HREF="http://ahts.sourceforge.net">http://ahts.sourceforge.net</A>) but am not having much luck. In
particular, I get the following error in the server error log (the
full backtrace is below):

[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Errors.py&quot;, line 9, in ?
    import exceptions
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: ImportError: Cannot re-init internal module exceptions

This is running in the following configuration:

Apache/1.3.19 (Unix) PHP/4.0.4pl1 mod_python/2.7.2 Python/2.0 configured

Anyone have an idea what is happening here? Any ideas on ameliorating this problem?

TIA,

    -tree


[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: Traceback (most recent call last):
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/mod_python/apache.py&quot;, line 176, in Dispatch
    module = import_module(module_name, _req)
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/mod_python/apache.py&quot;, line 334, in import_module
    module = imp.load_module(mname, f, p, d)
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/opt/www/htdocs/chinlex.py&quot;, line 2, in ?
    import MySQLdb, StringIO, ahts
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/__init__.py&quot;, line 33, in ?
    from utility import *
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/utility.py&quot;, line 29, in ?
    import writer
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/writer.py&quot;, line 33, in ?
    from parser import TemplateParser
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/parser.py&quot;, line 33, in ?
    from scanner import TemplateScanner
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/scanner.py&quot;, line 33, in ?
    from Plex import *
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/__init__.py&quot;, line 34, in ?
    from Lexicons import Lexicon, State
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Lexicons.py&quot;, line 13, in ?
    import Errors
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Errors.py&quot;, line 9, in ?
    import exceptions
[Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: ImportError: Cannot re-init internal module exceptions

-- 
Tom Emerson                                          Basis Technology Corp.
Sr. Sinostringologist                              <A HREF="http://www.basistech.com">http://www.basistech.com</A>
  &quot;Beware the lollipop of mediocrity: lick it once and you suck forever&quot;

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="008264.html">[mod_python] Any open-source applications?
</A></li>
	<LI>Next message: <A HREF="008269.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8266">[ date ]</a>
              <a href="thread.html#8266">[ thread ]</a>
              <a href="subject.html#8266">[ subject ]</a>
              <a href="author.html#8266">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
