<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] mod_python and Python 2.3
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20and%20Python%202.3&In-Reply-To=20030118115336.GA4522%40vader.boskant.nl">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="013375.html">
   <LINK REL="Next"  HREF="013376.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] mod_python and Python 2.3</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Josh Hoyt</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20and%20Python%202.3&In-Reply-To=20030118115336.GA4522%40vader.boskant.nl"
       TITLE="[mod_python] mod_python and Python 2.3">josh at janrain.com
       </A><BR>
    <I>Mon Jan 20 15:31:14 EST 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="013375.html">[mod_python] mod_python and Python 2.3
</A></li>
        <LI>Next message: <A HREF="013376.html">[mod_python] Query about client server interaction
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13378">[ date ]</a>
              <a href="thread.html#13378">[ thread ]</a>
              <a href="subject.html#13378">[ subject ]</a>
              <a href="author.html#13378">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i> This is a Python bug in Py_NewInterpreter() (or in some other place that
</I>&gt;<i> makes Py_NewInterpreter() fail). I sumbitted it to the Python developers
</I>&gt;<i> but I got no reply yet. The bug is described here:
</I>&gt;<i> 
</I>&gt;<i> <A HREF="http://sourceforge.net/tracker/index.php?func=detail&amp;aid=668708&amp;group_id=5470&amp;atid=105470">http://sourceforge.net/tracker/index.php?func=detail&amp;aid=668708&amp;group_id=5470&amp;atid=105470</A>
</I>
The problem appears to be that meta_path is not being
initialized in the new interpreter. Adding
_PyImportHooks_Init to Py_NewInterpreter seems to fix the
problem, initializing the new import hooks before trying to
import modules into the new interpreter.

Patch 671459 contains this fix.

Yeah for mod_python in Python 2.3!

Josh

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="013375.html">[mod_python] mod_python and Python 2.3
</A></li>
	<LI>Next message: <A HREF="013376.html">[mod_python] Query about client server interaction
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13378">[ date ]</a>
              <a href="thread.html#13378">[ thread ]</a>
              <a href="subject.html#13378">[ subject ]</a>
              <a href="author.html#13378">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
