<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] query regarding pyodbc
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20query%20regarding%20pyodbc&In-Reply-To=20090206091124.D98D16A45AD%40server1.edisphere.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025980.html">
   <LINK REL="Next"  HREF="025990.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] query regarding pyodbc</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20query%20regarding%20pyodbc&In-Reply-To=20090206091124.D98D16A45AD%40server1.edisphere.com"
       TITLE="[mod_python] query regarding pyodbc">graham.dumpleton at gmail.com
       </A><BR>
    <I>Fri Feb  6 08:47:05 EST 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="025980.html">[mod_python] query regarding pyodbc
</A></li>
        <LI>Next message: <A HREF="025990.html">[mod_python] i have problem accessing data from database using adodb
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25981">[ date ]</a>
              <a href="thread.html#25981">[ thread ]</a>
              <a href="subject.html#25981">[ subject ]</a>
              <a href="author.html#25981">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Recompile mod_python so it uses the correct installation of Python.
You cannot change it dynamically at run time. Use the '--with-python'
option to mod_python configure command. The argument to it should be
the path to 'python' executable for installation you want to use.

Graham

2009/2/6 rahul &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">rahul.warhekar at edisphere.com</A>&gt;:
&gt;<i> Hello
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Just Now, I got something as my .psp pages are pointing to my old version of
</I>&gt;<i> python2.3 which is also installed in my system.
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> For this I do export PYTHON=/usr/local/lib/python2.5
</I>&gt;<i>
</I>&gt;<i> But it was not useful I still got problem
</I>&gt;<i>
</I>&gt;<i> The error is
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> MOD_PYTHON ERROR
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> URI:            '/edi/redirect.psp'
</I>&gt;<i>
</I>&gt;<i> Location:       None
</I>&gt;<i>
</I>&gt;<i> Directory:      '/var/www/'
</I>&gt;<i>
</I>&gt;<i> Filename:       '/var/www/edi/redirect.psp'
</I>&gt;<i>
</I>&gt;<i> PathInfo:       ''
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Phase:          'PythonHandler'
</I>&gt;<i>
</I>&gt;<i> Handler:        'mod_python.psp'
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/usr/lib/python2.3/site-packages/mod_python/importer.py&quot;, line 1537,
</I>&gt;<i> in HandlerDispatch
</I>&gt;<i>
</I>&gt;<i>     default=default_handler, arg=req, silent=hlist.silent)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/usr/lib/python2.3/site-packages/mod_python/importer.py&quot;, line 1229,
</I>&gt;<i> in _process_target
</I>&gt;<i>
</I>&gt;<i>     result = _execute_target(config, req, object, arg)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/usr/lib/python2.3/site-packages/mod_python/importer.py&quot;, line 1128,
</I>&gt;<i> in _execute_target
</I>&gt;<i>
</I>&gt;<i>     result = object(arg)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/usr/lib/python2.3/site-packages/mod_python/psp.py&quot;, line 337, in
</I>&gt;<i> handler
</I>&gt;<i>
</I>&gt;<i>     p.run()
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/usr/lib/python2.3/site-packages/mod_python/psp.py&quot;, line 243, in
</I>&gt;<i> run
</I>&gt;<i>
</I>&gt;<i>     exec code in global_scope
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>   File &quot;/var/www/redirect.psp&quot;, line 18, in ?
</I>&gt;<i>
</I>&gt;<i>     import pyodbc
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> ImportError: dynamic module does not define init function (initpyodbc)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Is there any way to point to the newer version of python2.5
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> -----Original Message-----
</I>&gt;<i> From: Graham Dumpleton [mailto:<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>]
</I>&gt;<i> Sent: Friday, February 06, 2009 1:01 PM
</I>&gt;<i> To: rahul
</I>&gt;<i> Cc: <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mod_python at modpython.org</A>
</I>&gt;<i> Subject: Re: [mod_python] query regarding pyodbc
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> 2009/2/6 rahul &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">rahul.warhekar at edisphere.com</A>&gt;:
</I>&gt;<i>
</I>&gt;&gt;<i> Hello sir,
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Now import pyodbc is working from python console but when I import it from
</I>&gt;<i>
</I>&gt;&gt;<i> .psp pages it is giving error as
</I>&gt;<i>
</I>&gt;&gt;<i> ImportError : dynamic module does not define init function (initpyodbc)
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> I check  using nm pyodbc.so command it is giving initpyodbc function in
</I>&gt;&gt;<i> the
</I>&gt;<i>
</I>&gt;&gt;<i> list
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Now what may be the problem?
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> It is likely picking up wrong version still. Where is pyodbc package
</I>&gt;<i>
</I>&gt;<i> installed? Did you ensure that old broken versions were removed from
</I>&gt;<i>
</I>&gt;<i> the system?
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Graham
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> -----Original Message-----
</I>&gt;<i>
</I>&gt;&gt;<i> From: Graham Dumpleton [mailto:<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>]
</I>&gt;<i>
</I>&gt;&gt;<i> Sent: Friday, January 16, 2009 4:24 PM
</I>&gt;<i>
</I>&gt;&gt;<i> To: rahul
</I>&gt;<i>
</I>&gt;&gt;<i> Cc: <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mod_python at modpython.org</A>
</I>&gt;<i>
</I>&gt;&gt;<i> Subject: Re: [mod_python] query regarding pyodbc
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> 2009/1/16 rahul &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">rahul.warhekar at edisphere.com</A>&gt;:
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> I have run it from python console and it is giving same error.
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Then it is not a mod_python issue and you perhaps should ask on:
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i>  <A HREF="http://groups.google.com/group/comp.lang.python/topics?lnk">http://groups.google.com/group/comp.lang.python/topics?lnk</A>
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Now, I used nm command for pyodbc.so file and got the following output.
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> [<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">root at dbserver</A> site-packages]# nm pyodbc.so
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001600 A __bss_start
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000003ec t call_gmon_start
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001600 b completed.1
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000014fc d __CTOR_END__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000014f8 d __CTOR_LIST__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>         w __cxa_finalize@@GLIBC_2.1.3
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000004a8 t __do_global_ctors_aux
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00000410 t __do_global_dtors_aux
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000015f8 d __dso_handle
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001504 d __DTOR_END__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001500 d __DTOR_LIST__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 0000150c A _DYNAMIC
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001600 A _edata
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001604 A _end
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000004d8 T _fini
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 0000046c t frame_dummy
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000004f4 r __FRAME_END__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000015e8 A _GLOBAL_OFFSET_TABLE_
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>         w __gmon_start__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000003b4 T _init
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001508 d __JCR_END__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 00001508 d __JCR_LIST__
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>         w _Jv_RegisterClasses
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 000015fc d p.0
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Still I am not understanding what is the problem, please help.
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Like the message says, it cannot find in the C extension module the
</I>&gt;<i>
</I>&gt;&gt;<i> symbol 'initpyodbc', which is the entry point function for
</I>&gt;<i>
</I>&gt;&gt;<i> initialising the module.
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Thus the module has not been built properly or is broken in some way.
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Graham
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Thanks,
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Rahul
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> -----Original Message-----
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> From: Graham Dumpleton [mailto:<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>]
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Sent: Friday, January 16, 2009 2:55 PM
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> To: rahul
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Cc: <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mod_python at modpython.org</A>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Subject: Re: [mod_python] query regarding pyodbc
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> 2009/1/16 rahul &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">rahul.warhekar at edisphere.com</A>&gt;:
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Hello all,
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> I am using RedHat Enterprise 4 linux on which I have python 2.5.4 and
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> mod_python 3.3.1 .
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Now when I install pyodbc package and I try to import it it is giving me
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> an
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> error as
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> ImportError : dynamic module does not define init function (initpyodbc)
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> My pyodbc version is 2.1.14
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Any help regarding this will be greatly appreciated.
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Does it work when you try and import it from command line Python?
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Have you run 'nm' command on the .so file for the Python C extension
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> module to see whether that function (initpyodbc) exists in the file?
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> Graham
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i>
</I></PRE>



<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025980.html">[mod_python] query regarding pyodbc
</A></li>
	<LI>Next message: <A HREF="025990.html">[mod_python] i have problem accessing data from database using adodb
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25981">[ date ]</a>
              <a href="thread.html#25981">[ thread ]</a>
              <a href="subject.html#25981">[ subject ]</a>
              <a href="author.html#25981">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
