<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] SystemError: bad argument to internal function
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20SystemError%3A%20bad%20argument%20to%20internal%20function&In-Reply-To=88e286470706150255i139f2ea2p45eb8c83d137b9de%40mail.gmail.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="023852.html">
   <LINK REL="Next"  HREF="023854.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] SystemError: bad argument to internal function</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Clodoaldo</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20SystemError%3A%20bad%20argument%20to%20internal%20function&In-Reply-To=88e286470706150255i139f2ea2p45eb8c83d137b9de%40mail.gmail.com"
       TITLE="[mod_python] SystemError: bad argument to internal function">clodoaldo.pinto.neto at gmail.com
       </A><BR>
    <I>Fri Jun 15 06:59:20 EDT 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="023852.html">[mod_python] SystemError: bad argument to internal function
</A></li>
        <LI>Next message: <A HREF="023854.html">[mod_python] SystemError: bad argument to internal function
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23853">[ date ]</a>
              <a href="thread.html#23853">[ thread ]</a>
              <a href="subject.html#23853">[ subject ]</a>
              <a href="author.html#23853">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>2007/6/15, Graham Dumpleton &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>&gt;:
&gt;<i> Can you send the same POST content to a standard handler containing:
</I>
The error was triggered by user input I and can't reproduce it. It
happened only twice. To complicate it the same program meu_anuncio.py
handles 2 forms and I don't know which one triggered the error. One of
the forms uploads pictures. I have tested that program extensively and
found no problems. Tried again now in the production machine and I
can't trigger the error.

In some hours I will post the content of a non error-triggering POST.

Clodoaldo

&gt;<i>
</I>&gt;<i>   def handler(req):
</I>&gt;<i>     req.content_type = 'text/plain'
</I>&gt;<i>     print &gt;&gt; req, req.headers_in[&quot;content-length&quot;]
</I>&gt;<i>     print &gt;&gt; req, req.headers_in[&quot;content-type&quot;]
</I>&gt;<i>     print &gt;&gt; req
</I>&gt;<i>     print &gt;&gt; req, req.read()
</I>&gt;<i>     return apache.OK
</I>&gt;<i>
</I>&gt;<i> Am expecting the content type to be
</I>&gt;<i> &quot;application/x-www-form-urlencoded&quot; which is triggering parse_qsl().
</I>&gt;<i> The intent of the above script is to capture the POST data so you can
</I>&gt;<i> post it and we can then use it as test data for calling parse_qsl()
</I>&gt;<i> direct.
</I>&gt;<i>
</I>&gt;<i> At this point figuring that parse_qsl() has bug.
</I>&gt;<i>
</I>&gt;<i> While you do that I'll look through parse_qsl() code and see if I can
</I>&gt;<i> see any problem.
</I>&gt;<i>
</I>&gt;<i> Graham
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> On 15/06/07, Clodoaldo &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">clodoaldo.pinto.neto at gmail.com</A>&gt; wrote:
</I>&gt;<i> &gt; 2007/6/14, Graham Dumpleton &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>&gt;:
</I>&gt;<i> &gt; &gt; Did you ever sort this out?
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; No
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; &gt; Which sub revision of Python 2.4 are you using? The source code line
</I>&gt;<i> &gt; &gt; numbers don't match up with anything meaningful in Python 2.4.3 source
</I>&gt;<i> &gt; &gt; code that I have on hand.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; Python 2.4.4 in Fedora Core 6, Apache 2.2.4, mod_python 3.3.1
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; Clodoaldo
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; &gt; On 09/06/07, Clodoaldo &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">clodoaldo.pinto.neto at gmail.com</A>&gt; wrote:
</I>&gt;<i> &gt; &gt; &gt; I have this in my error log and I don't know what it means or what to do:
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] mod_python
</I>&gt;<i> &gt; &gt; &gt; (pid=15022, interpreter='carroarodo.com', phase='PythonHandler',
</I>&gt;<i> &gt; &gt; &gt; handler='~/_publisher.py'): Application error, referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] ServerName:
</I>&gt;<i> &gt; &gt; &gt; 'carroarodo.com', referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]
</I>&gt;<i> &gt; &gt; &gt; DocumentRoot: '/var/www/html/carroarodo.com', referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] URI:
</I>&gt;<i> &gt; &gt; &gt; '/meu_anuncio', referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] Location:
</I>&gt;<i> &gt; &gt; &gt; None, referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] Directory:
</I>&gt;<i> &gt; &gt; &gt; '/var/www/html/carroarodo.com/', referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] Filename:
</I>&gt;<i> &gt; &gt; &gt; '/var/www/html/carroarodo.com/meu_anuncio.py', referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] PathInfo:
</I>&gt;<i> &gt; &gt; &gt; '', referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225] Traceback
</I>&gt;<i> &gt; &gt; &gt; (most recent call last):, referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/importer.py&quot;, line
</I>&gt;<i> &gt; &gt; &gt; 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;<i> &gt; &gt; &gt; silent=hlist.silent), referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/importer.py&quot;, line
</I>&gt;<i> &gt; &gt; &gt; 1229, in _process_target\n    result = _execute_target(config, req,
</I>&gt;<i> &gt; &gt; &gt; object, arg), referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/importer.py&quot;, line
</I>&gt;<i> &gt; &gt; &gt; 1128, in _execute_target\n    result = object(arg), referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/var/www/html/carroarodo.com/_publisher.py&quot;, line 5, in handler\n
</I>&gt;<i> &gt; &gt; &gt; return publisher.handler(req), referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/publisher.py&quot;, line
</I>&gt;<i> &gt; &gt; &gt; 213, in handler\n    published = publish_object(req, object), referer:
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/publisher.py&quot;, line
</I>&gt;<i> &gt; &gt; &gt; 424, in publish_object\n    req.form = util.FieldStorage(req,
</I>&gt;<i> &gt; &gt; &gt; keep_blank_values=1), referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt; [Tue Jun 05 18:33:49 2007] [error] [client 200.155.85.225]   File
</I>&gt;<i> &gt; &gt; &gt; &quot;/usr/lib64/python2.4/site-packages/mod_python/util.py&quot;, line 225, in
</I>&gt;<i> &gt; &gt; &gt; __init__\n    pairs = parse_qsl(req.read(clen), keep_blank_val[Tue Jun
</I>&gt;<i> &gt; &gt; &gt; 05 18:33:49 2007] [error] [client 200.155.85.225] SystemError:
</I>&gt;<i> &gt; &gt; &gt; Objects/stringobject.c:3515: bad argument to internal function,
</I>&gt;<i> &gt; &gt; &gt; referer: <A HREF="http://carroarodo.com/meu_anuncio">http://carroarodo.com/meu_anuncio</A>
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; Any hints?
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; Regards, Clodoaldo Pinto Neto
</I>&gt;<i> &gt; &gt;
</I>&gt;<i> &gt;
</I>&gt;<i>
</I></PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="023852.html">[mod_python] SystemError: bad argument to internal function
</A></li>
	<LI>Next message: <A HREF="023854.html">[mod_python] SystemError: bad argument to internal function
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23853">[ date ]</a>
              <a href="thread.html#23853">[ thread ]</a>
              <a href="subject.html#23853">[ subject ]</a>
              <a href="author.html#23853">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
